xauusd_mart:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "xauusd_mart_dev.duckdb"
      threads: 4
    cloud:
      type: duckdb
      path: "md:xauusd_db?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 4
      extensions:
        - httpfs
        - json
